### ISSUE TITLE
Time format attribute

### ISSUE THREAD

**Issue by dmbjsn** [mattlewis92/angular-bootstrap-calendar#43]
Great work on this directive, really the best ng calendar out there! My users are mainly from Europe, so I like to go with 24h time rather than AM/PM.

I change this right now in the source on my local copy, but on bower update I have to do remember to repeat this. Do you have any plans for adding format attributes, like time (H:mm), date (for title use) etc.?

Thanks again for your nice work!
/dmbjsn

**Comment by mattlewis92** [comment]
I'm going to add a provider where you can globally configure all formatting of the calendar. Should get it in this weekend :)

**Comment by dmbjsn** [comment]
Very nice, thanks for quick reply!

**Comment by dmbjsn** [comment]
Hi,

I should probably make an issue on git, but just to let you know:
When use-iso-week is set to true, in ‘week view’, events on sundays are not showing. When it is set to false, the same is not happening with saturdays.

Thank you for this calendar, it is so useful!

Jason

**Comment by mattlewis92** [comment]
^ That last issue is now fixed in master. Going to add the configurable time format provider then release a new version :)

**Comment by mattlewis92** [comment]
This is now done and you can use it like this:
```javascript
angular.module('myModule')
  .config(function(calendarConfigProvider) {
  
    calendarConfigProvider.configureDateFormats({
      hour: 'HH:mm' //this will configure the hour view to display in 24 hour format rather than the default of 12 hour
    });
    
  });
```

**Comment by karentrevino** [comment]
Shouldn't it be 

```javascript
calendarConfigProvider.configureDateFormats({
      time: 'HH:mm' //this will configure the hour view to display in 24 hour format rather than the default of 12 hour
    });
```

? (time instead of hour)

**Comment by mattlewis92** [comment]
That's correct as it's an example of what you can change it too, rather than what the default is, as the comment next to it explains.

**Comment by karentrevino** [comment]
What I meant is that I tried to copy/paste so I could change hours from 1-12 AM/PM, so this is what I used 

```javascript
calendarConfigProvider.configureDateFormats({
      hour: 'hh:mm a' //this will configure the hour view to display in 24 hour format rather than the default of 12 hour
    });
```
However, that will not work as times are still shown in 24 hour format. This worked for me

```javascript
    calendarConfigProvider.setDateFormats({
        time: 'hh:mm a', //this will configure the hour view to display in 24 hour format rather than the default of 12 hour
    });
```

**Comment by mattlewis92** [comment]
Ah right I get what you mean now, I've updated the comment in the readme

**Comment by emilguareno** [comment]
Hey @mattlewis92, great work on the calendar! I've found it very helpful.

Just to let you know, the documentation still shows hour instead of time for the formatting. It took some time before I found this thread, it would help if you updated the documentation.

Thanks again!
